CREATE TABLE IF NOT EXISTS articles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    url character varying COLLATE pg_catalog."default" NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    body character varying COLLATE pg_catalog."default" NOT NULL,
    author character varying COLLATE pg_catalog."default",
    CONSTRAINT articles_title_key UNIQUE (title),
    CONSTRAINT articles_url_key UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS article_links
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_article integer NOT NULL,
    id_article_other integer NOT NULL,
    CONSTRAINT article_links_pkey PRIMARY KEY (id),
    CONSTRAINT article_links_id_article_id_article_other_key UNIQUE (id_article, id_article_other),
    CONSTRAINT article_links_id_article_fkey FOREIGN KEY (id_article)
        REFERENCES articles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT article_links_id_article_other_fkey FOREIGN KEY (id_article_other)
        REFERENCES articles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS article_tags
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_article integer NOT NULL,
    tag character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT article_tags_pkey PRIMARY KEY (id),
    CONSTRAINT article_tags_id_article_tag_key UNIQUE (id_article, tag),
    CONSTRAINT article_tags_id_article_fkey FOREIGN KEY (id_article)
        REFERENCES articles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);